name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Set NODE_ENV to Production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # Add debugging steps before build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm ci
          cd api && npm ci

      - name: Debug - List Current Directory
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Node modules size:"
          du -sh node_modules
          echo "API node modules size:"
          du -sh api/node_modules

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
          app_build_command: "npm run build"
          api_build_command: "npm run build"
          api_artifact_location: "dist"
          skip_api_build: false

      # Add post-build debugging
      - name: Debug - Check Build Output
        if: always()
        run: |
          echo "Dist directory contents:"
          ls -la dist || echo "dist directory not found"
          
          echo "Dist directory size:"
          du -sh dist || echo "dist directory not found"
          
          echo "Number of files in dist:"
          find dist -type f | wc -l || echo "dist directory not found"
          
          echo "API dist directory contents:"
          ls -la api/dist || echo "api/dist directory not found"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"